---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ksqldb.softlee.io
  resources:
  - ksqldbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ksqldb.softlee.io
  resources:
  - ksqldbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - ksqldb.softlee.io
  resources:
  - ksqldbclusters/status
  verbs:
  - get
  - patch
  - update
