apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
  labels:
    app: producer-api
spec:
  selector:
    matchLabels:
      app: producer-api
  template:
    metadata:
      name: producer-service
      labels:
        app: producer-api
    spec:
      containers:
      - name: producer-api
        imagePullPolicy: Never
        image: docker.io/library/producer-service
        ports:
          - containerPort: 8080
            name: apipod
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: KAFKA_SERVER
          value: demo-cp-kafka:9092
        - name: SCHEMA_REGISTRY_SERVER
          value: http://demo-cp-schema-registry:8081
        - name: KAFKA_TOPIC
          value: com.topic.in.order_created
        - name: POD_NAME
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name